---
title: "IDB Techsprint"
author: "Problem 3 - Group 2"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}

library(shiny)
library(tidyverse)

```


```{r}

# Datasets

url_dominican-proj <- "https://idb-air-techsprint.vercel.app/datasets/investment-projects-dom"
url_paraguay-budget <- "https://idb-air-techsprint.vercel.app/datasets/general-budget-pry"
url_paraguay-proj <- "https://idb-air-techsprint.vercel.app/datasets/investment-projects-pry"
url_paraguay-devplan <- "https://idb-air-techsprint.vercel.app/datasets/national-development-plan-pry"

## Additional datasets

url_dominican-opendata <- "https://datosabiertos.dgcp.gob.do/opendata/tablas"
url_dominican-contracdata <- "https://api.dgcp.gob.do/"
url_dominican-buyproc <- "https://api.dgcp.gob.do/opendata/emergencia/procesos.csv"
url_dominican-buycont <- "https://api.dgcp.gob.do/opendata/emergencia/contratos.csv"
url_paraguay-opendata <- "https://www.contrataciones.gov.py/datos/"
url_paraguay-contractdata <- "https://data.open-contracting.org/es/publication/63"


```

